title: Alison Holloway's Technical Writing Portfolio
email: alison.holloway@pm.me
description: >-
  Alison Holloway's technical writing porfolio. Includes writing examples and
  contact information.
domain: alison-holloway.github.io
baseurl: ''
url: 'https://alison-holloway.github.io/'
github_username: alison-holloway
linkedin_username: alison-holloway-au
theme: minima
plugins:
  - jekyll-feed
